### ISSUE TITLE
Blaník

### ISSUE THREAD

**Issue by peekaa** [kodi-czsk/plugin.audio.dmd-czech.play.cz#1]
Nešlo by přidat Rádio Blaník? Díky....

**Comment by jose1711** [comment]
v xml toto radio vobec nie je. web https://www.play.cz/radio-blanikcz skonci na 404. tak neviem..

**Comment by peekaa** [comment]
Aha, tak nic. Díky.

**Comment by peekaa** [comment]
Našel jsem toto:

http://ice.abradio.cz/blanikfm64.mp3
http://ice.abradio.cz/blanikfm128.mp3
